/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: suasanakreasi (https://sketchfab.com/suasanakreasi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/business-man-standing-d9ed9bb7baff4e03af19e439af1dd4d7
Title: Business Man Standing
*/
//C:\Users\wotbl\copy rest Preview\Restaurant-monitoring-React-and-Three.js-app\src\assets\3d\business_man_standing.glb







import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import ManScene from "../assets/3d/business_man_standing.glb"
export function Man(props) {
  const { nodes, materials } = useGLTF(ManScene);
  const { scene, animations } = useGLTF(ManScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh1_M_455555566666666_Material__2_0.geometry}
        material={materials.M_455555566666666_Material__2}
      //  scale={0.01}
      position={[8,0,-6]}
      scale={1.5}
      />

<primitive object={scene} />
    </group>
  );
}

useGLTF.preload("/business_man_standing.glb");
